# Description: docker compose file for core containers
# Author: Leon Stigter <lstigter@gmail.com>
# Last Updated: 2018-06-24
#
# run: docker-compose up -d 
#
version: "2.2"
services:

  jenkins:
    image: retgits/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - "$DOCKER_STORAGE/jenkins:/var/jenkins_home"
    restart: always
  
  gogs:
    image: gogs/gogs
    ports:
      - "3000:3000"
      - "10022:22"
    container_name: gogs
    volumes:
      - "$DOCKER_STORAGE/gogs:/data"
    restart: always
